### ISSUE TITLE
remove LocalCode from the CmsPage url

### ISSUE THREAD

**Issue by rzp-789** [monsieurbiz/SyliusCmsPagePlugin#38]
I would want to remove the localCode in Url for the page created with this bundle, do you know a way to do this properly ? I tried but everytime i can't refind my CmsPage if i removed the localCode on my Sylius Application. Thanks for your help.

**Comment by delyriand** [comment]
Hi @rzp-789,

have you tried removing the prefix on route in your `config/routes/monsieurbiz_sylius_cms_page_plugin.yaml`?

```
monsieurbiz_cms_page_admin:
    resource: "@MonsieurBizSyliusCmsPagePlugin/Resources/config/routing/admin.yaml"
    prefix: /%sylius_admin.path_name%

monsieurbiz_cms_page_shop:
    resource: "@MonsieurBizSyliusCmsPagePlugin/Resources/config/routing/shop.yaml"
```
